### ISSUE TITLE
能写一个搭建教程吗

### ISSUE THREAD

**Issue by cddehsy** [aoaostar/v8cdn-panel#1]
能写一个搭建教程吗

**Comment by aoaostar** [comment]
这是前端项目，直接使用releases里打包好的就行了
都是静态文件，有个nginx就能跑啊
和后端一起的话，放到后端项目的dist目录里就行了

**Comment by aoaostar** [comment]
![image](https://user-images.githubusercontent.com/86001674/132503438-ca470ad3-c8c5-4c43-90c6-659d4d072df6.png)
