### ISSUE TITLE
列表没有填满整个窗口

### ISSUE THREAD

**Issue by HanadaLee** [aoaostar/v8cdn-panel#2]
![1637334076(1)](https://user-images.githubusercontent.com/33758411/142644290-186e0176-ec51-47e8-9c93-a8fdf9920545.jpg)
![20211119225958](https://user-images.githubusercontent.com/33758411/142644058-12c1d714-542a-474d-a3c2-bf6bac8d556d.png)
si似乎这里没有填充整个页面，是代码判断高度出了问题么

**Comment by aoaostar** [comment]
哦哦，table写死了，没管大屏幕的
